"""Added ArticleStatus enum

Revision ID: 1240b8696b0b
Revises: be7ed0b87ea6
Create Date: 2025-03-25 08:49:41.660546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1240b8696b0b'
down_revision: Union[str, None] = 'be7ed0b87ea6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('editing_status', sa.Enum('public', 'admin_available', 'private', name='articlestatus'), nullable=False))
    op.drop_column('articles', 'public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('public', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('articles', 'editing_status')
    # ### end Alembic commands ###
