"""added the social media column

Revision ID: 9007bde0fc78
Revises: b9e9d447ad51
Create Date: 2025-04-28 23:02:09.481764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9007bde0fc78'
down_revision: Union[str, None] = 'b9e9d447ad51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_media',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=False),
    sa.Column('thumbnail', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_media_id'), 'social_media', ['id'], unique=False)
    op.create_index(op.f('ix_social_media_url'), 'social_media', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_social_media_url'), table_name='social_media')
    op.drop_index(op.f('ix_social_media_id'), table_name='social_media')
    op.drop_table('social_media')
    # ### end Alembic commands ###
